/**
 * Agent instructions generator — writes the per-agent instructions file
 * for each worktree during team launch.
 *
 * Each agent gets instructions with:
 * - Role and responsibilities
 * - File ownership boundaries
 * - Shared files protocol
 * - Project conventions (from .grove/config.json if it exists)
 * - User's task description
 * - Handoff protocol for out-of-scope changes
 *
 * The file is written to `<repo>/.grove/agents/`, which is git-excluded and
 * outside every worktree, and Claude Code loads it with
 * `--append-system-prompt` (see utils/claude-command.ts). Grove never writes
 * a CLAUDE.md into the worktree: that file may be tracked, and the
 * auto-commit and merge would carry an overwritten copy to the base branch.
 * The project's own CLAUDE.md in the worktree is still loaded by Claude Code
 * as usual; the main checkout's copy is only inlined when the worktree has
 * none (for example when CLAUDE.md is untracked).
 */

import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";
import type { AgentRole, TeamTemplate } from "./template-manager";
import type { ProjectConfig } from "./config-manager";
import { excludeGroveDir } from "./gitignore";
import { git, gitWrite } from "../utils/git";

export interface AgentInstructionsOptions {
    /** The agent role configuration */
    agent: AgentRole;
    /** The full team template (for cross-reference) */
    template: TeamTemplate;
    /** The user's task description */
    taskDescription: string;
    /** The team name (used for cross-agent references) */
    teamName: string;
    /** The main repo root (instructions are stored under its .grove/) */
    repoRoot: string;
    /** The agent's worktree path */
    worktreePath: string;
    /** Project config if available */
    projectConfig?: ProjectConfig;
    /** Shared files that multiple agents might need to touch */
    sharedFiles?: string[];
}

/** Footer prefix written at the end of every generated instructions file. */
const GENERATED_FOOTER = "*Generated by Grove at ";

function realOrResolved(p: string): string {
    try {
        return fs.realpathSync(p);
    } catch {
        return path.resolve(p);
    }
}

/**
 * Where the instructions file for a worktree lives:
 * `<repo>/.grove/agents/<worktree-name>-<hash>.md`. The hash of the
 * worktree's real path keeps two worktrees with the same folder name apart.
 */
export function agentInstructionsPath(repoRoot: string, worktreePath: string): string {
    const real = realOrResolved(worktreePath);
    const slug = path.basename(real).replace(/[^\w.-]/g, "-");
    const hash = crypto.createHash("sha1").update(real).digest("hex").slice(0, 8);
    return path.join(repoRoot, ".grove", "agents", `${slug}-${hash}.md`);
}

/**
 * Write an agent's instructions to `.grove/agents/` and return the path.
 * Nothing is written inside the worktree.
 */
export function writeAgentInstructions(options: AgentInstructionsOptions): string {
    const content = buildAgentInstructions(options);
    const filePath = agentInstructionsPath(options.repoRoot, options.worktreePath);
    excludeGroveDir(options.repoRoot);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
    return filePath;
}

/**
 * True if the text is an agent instructions file generated by Grove
 * (this version, or the CLAUDE.md that Grove 0.6.0 and earlier wrote into
 * worktrees).
 */
export function isGroveGeneratedInstructions(content: string): boolean {
    const firstLine = content.split("\n", 1)[0] ?? "";
    return /^# .+ \u2014 Grove Agent\s*$/.test(firstLine) && content.includes(GENERATED_FOOTER);
}

/**
 * Undo a CLAUDE.md that Grove 0.6.0 or earlier generated inside a worktree,
 * so it is never committed or merged. Grove wrote through whatever
 * CLAUDE.md resolves to, so a symlinked CLAUDE.md (for example to
 * AGENTS.md) and a differently-cased `claude.md` on a case-insensitive disk
 * are handled too. A tracked file is restored from HEAD; an untracked one is
 * deleted. Left alone: a CLAUDE.md Grove did not generate, one whose HEAD
 * copy is itself Grove-generated (the working copy is then an ordinary
 * edit), and a target outside the worktree. Returns true if anything was
 * undone.
 */
export async function discardLegacyGeneratedClaudeMd(worktreePath: string): Promise<boolean> {
    const claudeMdPath = path.join(worktreePath, "CLAUDE.md");
    let content: string;
    let target: string;
    try {
        content = fs.readFileSync(claudeMdPath, "utf-8");
        target = fs.realpathSync.native(claudeMdPath);
    } catch {
        return false;
    }
    if (!isGroveGeneratedInstructions(content)) return false;

    // This was the agent's only copy of its instructions: keep it where
    // 0.6.1 looks for them, so a relaunch still gets its role and task.
    await migrateLegacyInstructions(worktreePath, content);

    const rel = path.relative(fs.realpathSync.native(worktreePath), target).replace(/\\/g, "/");
    if (!rel || rel.startsWith("../") || path.isAbsolute(rel)) return false;

    const indexed = (
        await git(["ls-files", "-z", "--", `:(icase)${rel}`], worktreePath, { trim: false })
    ).split("\0").filter((name) => name.toLowerCase() === rel.toLowerCase());
    const tracked = indexed[0];

    let headContent: string | undefined;
    if (tracked) {
        try {
            headContent = await git(["show", `HEAD:${tracked}`], worktreePath);
        } catch {
            headContent = undefined;
        }
    }

    if (tracked && headContent !== undefined) {
        if (isGroveGeneratedInstructions(headContent)) return false;
        await gitWrite(["checkout", "HEAD", "--", tracked], worktreePath);
    } else {
        // Unstage it first in case it was added to the index.
        if (tracked) {
            await gitWrite(["rm", "--cached", "--quiet", "--", tracked], worktreePath);
        }
        fs.rmSync(target, { force: true });
    }
    return true;
}

/**
 * Save instructions found in a 0.6.0 CLAUDE.md to `.grove/agents/` of the
 * main checkout, unless an instructions file already exists there.
 */
async function migrateLegacyInstructions(worktreePath: string, content: string): Promise<void> {
    try {
        const list = await git(["worktree", "list", "--porcelain"], worktreePath);
        const first = list.split("\n").find((line) => line.startsWith("worktree "));
        if (!first) return;
        const repoRoot = first.slice("worktree ".length);
        const file = agentInstructionsPath(repoRoot, worktreePath);
        if (fs.existsSync(file)) return;
        excludeGroveDir(repoRoot);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
    } catch {
        // Best effort: the undo below must still happen.
    }
}

/**
 * Build the agent instructions text (without writing to disk).
 */
export function buildAgentInstructions(options: AgentInstructionsOptions): string {
    const {
        agent,
        template,
        taskDescription,
        teamName,
        repoRoot,
        worktreePath,
        projectConfig,
        sharedFiles = [],
    } = options;

    const sections: string[] = [];

    // ── Header ──────────────────────────────────────
    sections.push(`# ${agent.displayName} — Grove Agent`);
    sections.push("");
    sections.push(`> **Team:** ${template.name} | **Role:** ${agent.role} | **Session:** ${teamName}`);
    sections.push("");
    sections.push(
        "**IMPORTANT: These agent-specific instructions take priority over any " +
        "project-level CLAUDE.md instructions regarding file ownership and boundaries. " +
        "YOU MUST respect the file ownership rules below — do not modify files " +
        "outside your assigned ownership patterns.**"
    );
    sections.push("");

    // ── Task Description ────────────────────────────
    if (taskDescription) {
        sections.push("## Task");
        sections.push("");
        sections.push(taskDescription);
        sections.push("");
    }

    // ── Role & Responsibilities ─────────────────────
    sections.push("## Your Role");
    sections.push("");
    sections.push(agent.prompt);
    sections.push("");

    if (agent.readOnly) {
        sections.push(
            "**IMPORTANT: You are in READ-ONLY review mode.** " +
            "Do NOT modify any source files. Instead, write your findings to `REVIEW.md` " +
            "in the root of this worktree."
        );
        sections.push("");
    }

    // ── File Ownership ──────────────────────────────
    sections.push("## File Ownership");
    sections.push("");

    if (agent.ownership.length > 0) {
        sections.push("**YOU MUST** focus your work on these file patterns — they are yours:");
        sections.push("");
        for (const pattern of agent.ownership) {
            sections.push(`- \`${pattern}\``);
        }
        sections.push("");
    }

    // List other agents' ownership for reference
    const otherAgents = template.agents.filter((a) => a.role !== agent.role);
    const otherOwnedAgents = otherAgents.filter((a) => a.ownership.length > 0);
    if (otherOwnedAgents.length > 0) {
        sections.push(
            "**IMPORTANT: YOU MUST NOT modify** files owned by other agents. " +
            "If you need changes in these files, use the Handoff Protocol below instead:"
        );
        sections.push("");
        for (const other of otherOwnedAgents) {
            const patterns = other.ownership.map((p) => `\`${p}\``).join(", ");
            sections.push(`- **${other.displayName}** (${other.role}): ${patterns}`);
        }
        sections.push("");
    }

    // ── Shared Files Protocol ───────────────────────
    if (sharedFiles.length > 0) {
        sections.push("## Shared Files Protocol");
        sections.push("");
        sections.push(
            "**IMPORTANT:** The following files may be needed by multiple agents. " +
            "**YOU MUST NOT modify these directly.** Instead, document your required " +
            "changes in `SHARED-CHANGES.md` in the root of this worktree."
        );
        sections.push("");
        for (const file of sharedFiles) {
            sections.push(`- \`${file}\``);
        }
        sections.push("");
        sections.push("Format for `SHARED-CHANGES.md`:");
        sections.push("");
        sections.push("```markdown");
        sections.push(`## Changes needed by ${agent.displayName}`);
        sections.push("");
        sections.push("### <filename>");
        sections.push("- What to add/change and why");
        sections.push("```");
        sections.push("");
    }

    // ── Handoff Protocol ────────────────────────────
    if (!agent.readOnly) {
        sections.push("## Handoff Protocol");
        sections.push("");
        sections.push(
            "If you need changes in files you don't own, create a `HANDOFF.md` " +
            "file in the root of this worktree with the following format:"
        );
        sections.push("");
        sections.push("```markdown");
        sections.push(`## Handoff from ${agent.displayName}`);
        sections.push("");
        sections.push("### For: <target agent role>");
        sections.push("- File: <path>");
        sections.push("- Change needed: <description>");
        sections.push("- Why: <reasoning>");
        sections.push("```");
        sections.push("");
    }

    // ── Project Conventions ─────────────────────────
    if (projectConfig?.conventions) {
        const conv = projectConfig.conventions;
        sections.push("## Project Conventions");
        sections.push("");
        if (conv.framework) sections.push(`- **Framework:** ${conv.framework}`);
        if (conv.testFramework) sections.push(`- **Testing:** ${conv.testFramework}`);
        if (conv.linter) sections.push(`- **Linting:** ${conv.linter}`);
        sections.push("");
    }

    // ── Extra Instructions ──────────────────────────
    if (agent.claudeMdExtra) {
        sections.push("## Additional Instructions");
        sections.push("");
        sections.push(agent.claudeMdExtra);
        sections.push("");
    }

    // ── Project CLAUDE.md, if the worktree lacks one ─
    // Claude Code loads a CLAUDE.md that is checked out in the worktree by
    // itself. An untracked one exists only in the main checkout, so inline it.
    const worktreeHasClaudeMd =
        fs.existsSync(path.join(worktreePath, "CLAUDE.md")) ||
        fs.existsSync(path.join(worktreePath, ".claude", "CLAUDE.md"));
    const mainClaudeMd = worktreeHasClaudeMd ? undefined : readMainClaudeMd(repoRoot);
    if (mainClaudeMd) {
        sections.push("## Project-Level Instructions (from main repo)");
        sections.push("");
        sections.push(mainClaudeMd);
        sections.push("");
    }

    // ── Footer ──────────────────────────────────────
    sections.push("---");
    sections.push(
        `${GENERATED_FOOTER}${new Date().toISOString()}*`
    );
    sections.push("");

    return sections.join("\n");
}

/**
 * Read CLAUDE.md from the main checkout, unless it is one Grove generated.
 */
function readMainClaudeMd(repoRoot: string): string | undefined {
    try {
        const content = fs.readFileSync(path.join(repoRoot, "CLAUDE.md"), "utf-8").trim();
        return content && !isGroveGeneratedInstructions(content) ? content : undefined;
    } catch {
        return undefined;
    }
}
